swagger: '2.0'
info:
  title: Portail d'intéractions du simulateur de traffic Road Concept
  description: Aide à l'utilisation de l'API
  version: "0.1"
host: localhost:8080
schemes:
  - http
produces:
  - application/json

parameters:
  mapUUID:
    name: mapUUID
    in: path
    required: true
    type: string
    format: uuid

paths:
  /login:
    post:
      parameters:
        - name: credentials
          in: body
          description: Identifiants de l'utilisateur souhaitant se connecter.
          required: true
          schema:
            $ref: '#/definitions/UserCredentials'
      tags:
        - Connexion
      responses:
        204:
          description: Utilisateur corretement authentifié. Un cookie a été retourné et doit être envoyé au serveur à chaque prochaine requête.
        400:
          $ref: '#/responses/400'
        401:
          $ref: '#/responses/401'
        403:
          $ref: '#/responses/403'
        500:
          $ref: '#/responses/500'

  /api/logout:
    post:
      tags:
        - Connexion
      responses:
        204:
          description: Utilisateur corretement déconnecté.
        400:
          $ref: '#/responses/400'
        401:
          $ref: '#/responses/401'
        403:
          $ref: '#/responses/403'
        500:
          $ref: '#/responses/500'

responses:
  '400':
    description: Mauvaise requête. Vérifier les paramètres et les formats.
    schema :
      $ref: '#/definitions/RestException'
  '401':
    description: Authentification nécéssaire. Voir méthode POST /login.
    schema :
      $ref: '#/definitions/RestException'
  '403':
    description: Accès refusé.
    schema:
      $ref: '#/definitions/RestException'
  '500':
    description: Erreur interne au serveur. Contacter un administrateur de l'API.

definitions:
  RestException:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string

  UserCredentials:
    properties:
      username: # code HTTP
        type: string
      password:
        type: string
        format: password

