swagger: '2.0'
info:
  title: Road-Concept API
  description: Aide à l'utilisation de l'API de Road-Concept
  version: "0.1"
# the domain of the service
host: a.determiner.fr
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /
produces:
  - application/json
paths:
  /maps:
    get:
      summary: Obtenir les cartes d'un utilisateur
      description: |
        Donne la liste des cartes d'un utilisateur, le fichier contient toutes les informations de base de chaques cartes.
      parameters:
        - name: username
          in: query
          description: Login du client
          required: true
          type: string
          format: username
        - name: password
          in: query
          description: Mot de passe du client
          required: true
          type: string
          format: password
      tags:
        - Maps
      responses:
        200:
          description: Un tableau de carte
          schema:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                  description: Nom de la carte
                id:
                  type: string
                  description: Id de la carte
                img_url:
                  type: string
                  description: URL de l'image associé à cette carte
        401:
          description: Une authentification est nécessaire pour accéder à la ressource.
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Obtenir les cartes d'un utilisateur
      description: |
        Donne la liste des cartes d'un utilisateur, le fichier contient toutes les informations de base de chaques cartes.
      parameters:
        - name: username
          in: formData
          description: Login du client
          required: true
          type: string
          format: username
        - name: password
          in: formData
          description: Mot de passe du client
          required: true
          type: string
          format: password
        - name: mapName
          in: formData
          description: Nom de la carte à créer
          required: true
          type: string
        - name: mapCountryBorder
          in: formData
          description: La map doit-elle contenir les frontières des pays ?
          required: true
          type: boolean
        - name: mapIMG
          in: formData
          required: false
          description: Une image optionnelle pour représenter la map.
          type: file
      tags:
        - Maps
      responses:
        200:
          description: Réponse de succés d'ajout. Le message contient l'ID de la nouvelle map.
          schema:
            $ref: "#/definitions/Success"
        401:
          description: Une authentification est nécessaire pour accéder à la ressource.
          schema:
            $ref: '#/definitions/Error'

definitions:
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string

  Success:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string