version: '2'

services:
  frontend:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "backend"
  backend:
    build: ./roadconcept
    ports:
      - "8080:8080"
    links:
      - "postgresql"
      - "mongodb"
  postgresql:
    build: ./postgresql
    environment:
      POSTGRES_PASSWORD: bonjour
    volumes:
      - /var/roadconcept/postgresql/data:/var/lib/postgresql/data
  mongodb:
    build: ./mongodb
    volumes:
      - /var/roadconcept/mongodb/data:/data/db:rw


