version: '2'

services:
  backend:
    build: ./roadconcept
    ports:
      - "8080:8080"
    links:
      - "postgresql"
      - "mongodb"
  postgresql:
    build: ./postgresql
    environment:
      POSTGRES_PASSWORD: bonjour
    ports:
      - "5432:5432"
  mongodb:
    build: ./mongodb
    ports:
      - "27017:27017"

