version: '2'

services:
  web:
    build: ./roadconcept
    ports:
      - "8080:8080"
    links:
      - "postgresql"
      - "mongodb"
  postgresql:
    build: ./postgresql
    environment:
      POSTGRES_PASSWORD: bonjour
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  mongodb:
    image: mongo
    volumes:
      - ./mongodb/data:/data/db:rw
