version: '2'

services:
  backend:
    build: ./roadconcept
    ports:
      - "8080:8080"
    links:
      - "postgresql"
      - "mongodb"
  postgresql:
    build: ./postgresql
    environment:
      POSTGRES_PASSWORD: bonjour
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  mongodb:
    build: ./mongodb
    volumes:
      - ./mongodb/data:/data/db:rw
    ports:
      - "27017:27017"
  frontend:
    build: ./nginx
    ports:
      - "80:80"

